# Eureka 사용을 위한 포트 설정
server:
  port: 0

# Eureka Client 설정
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://127.0.0.1:8761/eureka/

spring:
  # Eureka 사용을 위한 서비스명 설정
  application:
    name: menu-service
  # JDBC 설정
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  # H2 Database 설정
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true

# Springdoc 설정
springdoc:
  swagger-ui:
    path: /api-specification.html