spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: localhost:9200
#  elasticsearch:
#    username: elastic
#    password: roffjrtl8!
#    uris:
#      localhost:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#    password: