server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    serverUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" # Front's end-point
            allowedMethods: "*"
            allowed-headers: "*"
            exposed-headers: "*"
            allow-credentials: true