server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #  data:
  #    redis:
  #      host: localhost
  #      port: 6379
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" # Front's end-point
            allowedMethods: "*"
            allowed-headers: "*"
            exposed-headers: "*"
            allow-credentials: true
      routes:
        - id: menu-service
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menus/**
        - id: recommend-service
          uri: lb://RECOMMEND-SERVICE
          predicates:
            - Path=/recommends/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**