drop table if exists menu cascade;
drop table if exists store cascade;
drop sequence if exists store_seq;
create sequence store_seq start with 1 increment by 50;
create table menu (
    sale_price numeric(38,2),
    store_price numeric(38,2),
    take_out_price numeric(38,2),
    temperature tinyint check (temperature between 0 and 1),
    created_date timestamp(6) not null,
    menu_id bigint generated by default as identity,
    modified_date timestamp(6) not null,
    category varchar(255) check (category in ('COFFEE','DECAFFEINE_COFFEE','MILK_TEA_AND_LATTE','JUICE_AND_DRINK','TEA_AMD_ADE','BREAD','DESSERT','MD')),
    created_by varchar(255) not null,
    description varchar(255),
    flag_type varchar(255) check (flag_type in ('NEW','BEST','SALE','NONE')),
    modified_by varchar(255) not null,
    status varchar(255) check (status in ('SELLING','SOLD_OUT','CLOSED','HIDE')),
    sub_title varchar(255),
    thumbnail_url varchar(255),
    title varchar(255),
    primary key (menu_id)
);

create table store (
    id bigint not null,
    address varchar(255),
    name varchar(255),
    thumbnail_url varchar(255),
    primary key (id)
);